### PR TITLE
new event lines/area plot in topo_timecourse

### PR DESCRIPTION
**Pull request by jelmerborst**
output

### CODE REVIEW

**Comment by jelmerborst** [comment]
made vlims consistent across topos and added optional color bar.
output

**Comment by jelmerborst** [comment]
output

**Comment by jelmerborst** [comment]
8backward
7evbackward

**Comment by jelmerborst** [comment]
do not merge this yet, apparently it works perfectly if magnify == 2, but not otherwise
magni1

**Comment by jelmerborst** [comment]
Finally fixed:

Single magnify = 2:
single

Multiple magnify = 1:
magnify1

Multiple magnify = 1.5:
magnify15

Multiple magnify = 3:
magnify3

**Comment by jelmerborst** [comment]
To summarize, changes to original:
- added event_lines/areas
- added cbar across max 2 rows
- set vmin vmax based on all topos, by default symmetric around 0
- height of fig now depends on magnify setting
- magnify no longer shifts topos

**Review by GWeindel — APPROVED** [review]
Everything looks fine!

**Pull request merged**
